# Generated by Django 5.1.4 on 2025-03-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/default_profile_image.png', null=True, upload_to='profile_pics/'),
        ),
    ]
