# Generated by Django 5.1.4 on 2025-03-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image/'),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
